print("Christine Luz"); 
print("Tampus,Boac,Marinduque"); 
print("April 9, 2001"); 
print("Marinduque State College"); 
print("Bachelor of Science in Information Tachnology"); 
print("Second year - Section D"); 
print("Binge watching movies"); 
print("Watch serial killer documentaries"); 
print("Watch satisfying videos on the internet"); 
print("Sleeping"); 
print("Reading random books online"); 